### ISSUE TITLE
Assessment Result

### ISSUE THREAD

**Issue by francepack** [cunninghamge/mod_0_skills#1]
@cunninghamge 
You performed well enough on the assessment to merit a chance to make some changes that can promote you to `technical ready`. Please make the following updates by EOD Sunday:

- In your first class, I think the naming for `includes` and `add_ons` could be more clear. For attribute `includes`, think about what it is this array actually contains, and go that direction with the name. Then, perhaps your method would just be to add one of those... `add_ons` seems like kind of a noun-like name, not really using `add` in an active way.

- In your second class, you can remove your class name from an attribute name, and method `run_out_of` leaves me wondering .... out of what? I think this name could use an active word `remove` or `deplete` to be a bit more descriptive.

Let me know if you have questions or if I can clarify anything.

**Comment by cunninghamge** [comment]
I made some changes per your suggestions but definitely let me know if there are other things I can do to improve. 

Also, this is me touching "Issues" for the first time so hopefully closing is the right thing to do!
